language: node_js
node_js:
  - "8"
script:
  - npm run test
before_deploy:
  - npm run build
deploy:
  email: zpdong93@gmail.com
  name: Primo
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master